import { Geist, Geist_Mono, Noto_Serif_JP } from "next/font/google";
import "./globals.css";
import "./styles/mobile.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Japanese calligraphy-like serif (closest free option)
const notoSerifJp = Noto_Serif_JP({
  variable: "--font-calligraphy",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, viewport-fit=cover",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${notoSerifJp.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
